steps:
  # Build the container image
  - name: "asia.gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "asia.gcr.io/arched-hybrid-368713/iotcicd-skripsi1", "."]
  # Push the container image to Container Registry
  - name: "asia.gcr.io/cloud-builders/docker"
    args: ["push", "asia.gcr.io/arched-hybrid-368713/iotcicd-skripsi1"]
  # Deploy container image to Cloud Run
  - name: "asia.gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "iotcicd-skripsi1",
        "--image",
        "asia.gcr.io/arched-hybrid-368713/iotcicd-skripsi1",
        "--region",
        "asia-east1",
        "--platform",
        "managed",
        "--port",
        "80",
      ]
images:
  - asia.gcr.io/arched-hybrid-368713/iotcicd-skripsi1
